### ISSUE TITLE
Missing clusterIssuer when TLS provider is `secret` but certManager is configured

### ISSUE THREAD

**Issue by stefanoghinelli** [sighupio/distribution#421]
### Describe the bug
In the furyctl.yaml, when the `certManager` key is present in the ingress module configuration but the TLS provider is set to `secret`, the clusterIssuer resource is not included. The current template condition only checks if the provider is `certManager`, but it should include the clusterIssuer resource whenever the `ingress.certManager` key exists, regardless of the TLS provider.

### To Reproduce
1. Create a `furyctl.yaml` file with the following ingress configuration:
```yaml
ingress:
  baseDomain: internal.myhost.com
  nginx:
    type: dual
    tls:
      provider: secret
      secret:
        cert: "{file://./secrets/tls/tls.crt}"
        key: "{file://./secrets/tls/tls.key}"
        ca: "{file://./secrets/tls/ca.crt}"
    certManager:
      clusterIssuer:
        name: letsencrypt-fury
```
2. Deploy using furyctl
3. Check that the clusterIssuer resource is not included due to the condition:
`{{- if eq .spec.distribution.modules.ingress.nginx.tls.provider "certManager" }}`

### Expected behavior
The `resources/cert-manager-clusterissuer.yaml` should be included whenever the `ingress.certManager` key exists in the configuration, regardless of the TLS provider setting.

### Screenshots
None

### Software versions
furyctl v0.32.4
SIGHUP distribution v1.32.0

### Additional context
None
